# Generated by Django 2.1.1 on 2019-06-03 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extprivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('nationality', models.CharField(blank=True, max_length=20, null=True, verbose_name='国籍')),
                ('nation', models.CharField(blank=True, max_length=20, null=True, verbose_name='民族')),
                ('nationplace', models.CharField(blank=True, max_length=20, null=True, verbose_name='籍贯')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身高')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='体重')),
                ('blood', models.CharField(blank=True, max_length=2, null=True, verbose_name='血型')),
                ('marital', models.BooleanField(default=False, verbose_name='婚姻')),
            ],
            options={
                'db_table': 'hr_extprivate',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeno',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='员工编号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='entry',
            field=models.DateField(blank=True, null=True, verbose_name='入职'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave',
            field=models.DateField(blank=True, null=True, verbose_name='离职'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='hr_department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='hr_employee',
        ),
        migrations.AlterModelTable(
            name='employee_department',
            table='hr_employee_department',
        ),
        migrations.AlterModelTable(
            name='extattr',
            table='hr_extattr',
        ),
        migrations.AlterModelTable(
            name='hrconfigs',
            table='hr_hrconfigs',
        ),
        migrations.AlterModelTable(
            name='user_sign_log',
            table='hr_user_sign_log',
        ),
        migrations.AddField(
            model_name='extprivate',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privateid', to='hr.employee', verbose_name='员工ID'),
        ),
    ]
