# Generated by Django 2.1.1 on 2019-06-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20190603_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='extattr',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标题'),
        ),
    ]
