# Generated by Django 2.1.1 on 2019-05-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companycode', models.CharField(blank=True, max_length=128, null=True, verbose_name='企业编码')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='企业名称')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='地址')),
                ('postal', models.CharField(blank=True, max_length=8, null=True, verbose_name='邮政编码')),
                ('tel', models.CharField(blank=True, max_length=16, null=True, verbose_name='电话')),
                ('fex', models.CharField(blank=True, max_length=16, null=True, verbose_name='传真')),
                ('web', models.CharField(blank=True, max_length=128, null=True, verbose_name='网址')),
                ('mail', models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('corpid', models.CharField(max_length=128, null=True, verbose_name='企业ID')),
            ],
        ),
        migrations.CreateModel(
            name='wxsecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='名称')),
                ('agentid', models.IntegerField(null=True, verbose_name='微信应用ID')),
                ('corpsecret', models.CharField(max_length=64, null=True, verbose_name='API密钥')),
                ('token', models.CharField(max_length=256, null=True, verbose_name='Token')),
                ('expirestime', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
            ],
        ),
    ]
