# Generated by Django 2.1.4 on 2019-05-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkinout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0, verbose_name='userid')),
                ('checktime', models.DateTimeField(blank=True, null=True, verbose_name='datatime')),
                ('checktype', models.CharField(blank=True, max_length=1, null=True, verbose_name='checktype')),
                ('verifycode', models.IntegerField(default=0, verbose_name='verifycode')),
                ('sensorid', models.CharField(blank=True, max_length=5, null=True, verbose_name='sensorid')),
                ('memoinfo', models.CharField(blank=True, max_length=30, null=True, verbose_name='memoinfo')),
                ('workcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='workcode')),
                ('sn', models.CharField(blank=True, max_length=20, null=True, verbose_name='SN')),
                ('userextfmt', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='userextfmt')),
                ('pin', models.CharField(blank=True, max_length=20, null=True, verbose_name='pin')),
            ],
            options={
                'db_table': 'att_checkinout',
            },
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24, null=True, verbose_name='班次')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
            ],
            options={
                'db_table': 'att_classes',
            },
        ),
        migrations.CreateModel(
            name='extemployeeatt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=20, null=True, verbose_name='pin')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='员工ID')),
            ],
            options={
                'db_table': 'att_extemployeeatt',
            },
        ),
    ]
