# Generated by Django 2.1.4 on 2019-05-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('dateend', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('adddate', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('moddate', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classes', verbose_name='班次ID')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='员工ID')),
            ],
            options={
                'db_table': 'att_classlist',
            },
        ),
    ]
