# Generated by Django 2.1.4 on 2019-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_classlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidayname', models.CharField(max_length=20, verbose_name='节日名')),
                ('starttime', models.DateField(verbose_name='开始日期')),
                ('duration', models.IntegerField(default=1, verbose_name='持续天数')),
                ('holidaytype', models.IntegerField(default=2, verbose_name='日期类型')),
                ('quotient', models.IntegerField(default=2, verbose_name='系数')),
            ],
            options={
                'db_table': 'att_holiday',
            },
        ),
    ]
