# Generated by Django 2.1.4 on 2019-05-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_timesolt'),
    ]

    operations = [
        migrations.CreateModel(
            name='classsolt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classes')),
                ('timesoltid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.timesolt')),
            ],
            options={
                'db_table': 'att_classsolt',
            },
        ),
    ]
