# Generated by Django 2.1.4 on 2019-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holidaytype',
            field=models.IntegerField(default=2, verbose_name='类型'),
        ),
    ]
