# Generated by Django 2.1.4 on 2019-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190521_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效的'),
        ),
    ]
