# Generated by Django 2.1.4 on 2019-05-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_holiday_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='active',
            field=models.BooleanField(default=True, verbose_name='有效的'),
        ),
    ]
